Repository HerculesWS/Hercules, pull requests merged in 2018-06, with the labels that each got.

#2038 Improve msgstring table usage
  src/map/Makefile.in
  src/map/clif.c
  src/map/clif.h
  src/map/messages.h
  src/map/messages_main.h
  src/map/messages_re.h
  src/map/messages_zero.h
  src/map/party.c
  src/map/pc.c
  src/map/script.c
  src/map/skill.c
  src/plugins/HPMHooking.c
Labels: status:code-review

#842 Add new *pcblock script command
  doc/script_commands.txt
  src/map/atcommand.c
  src/map/battle.c
  src/map/clif.c
  src/map/pc.c
  src/map/pc.h
  src/map/script.c
  src/map/script.h
  src/map/status.c
  src/map/unit.c
Labels: component:core, component:scripts, status:code-review, type:enhancement

#2059 Fix the skill element for levels above the MAX_SKILL_LEVEL
  src/map/skill.c
Labels: component:mechanics:skills, severity:2-fair, type:bug

#2057 Fix map flag pvp_nocalcrank if use at or script command for enable pvp.
  src/map/atcommand.c
  src/map/script.c
Labels: status:code-review

#2036 Conversion of exp.txt to Libconfig
  db/pre-re/exp.txt
  db/pre-re/exp_group_db.conf
  db/pre-re/job_db.conf
  db/re/exp.txt
  db/re/exp_group_db.conf
  db/re/job_db.conf
  src/map/pc.c
  src/map/pc.h
  src/map/status.c
Labels: component:core, status:code-review, type:enhancement

#2004 Implementation of stylist ui
  conf/messages.conf
  db/pre-re/item_db.conf
  db/re/item_db.conf
  db/stylist_db.conf
  doc/script_commands.txt
  src/map/clif.c
  src/map/clif.h
  src/map/itemdb.c
  src/map/map.h
  src/map/packets.h
  src/map/packets_struct.h
  src/map/script.c
Labels: component:client-interface, status:code-review

#2072 Fix clif_parse_OpenVending with empty items list.
  src/map/clif.c
Labels: status:code-review, type:bug

#2064 update packets and message table for clients 20180530 to 20180612
  src/char/char.c
  src/login/lclif.p.h
  src/map/clif.c
  src/map/clif.h
  src/map/messages_main.h
  src/map/messages_re.h
  src/map/messages_zero.h
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_shuffle_main.h
  src/map/packets_struct.h
  src/map/pc.c
  src/map/script.c
Labels: status:code-review

#1924 Update Instance generating behaviour
  npc/instances/EndlessTower.txt
  npc/instances/NydhoggsNest.txt
  npc/instances/OrcsMemory.txt
  npc/instances/SealedShrine.txt
  npc/re/instances/BakonawaLake.txt
  npc/re/instances/BangungotHospital.txt
  npc/re/instances/BuwayaCave.txt
  npc/re/instances/EclageInterior.txt
  npc/re/instances/HazyForest.txt
  npc/re/instances/MalangdoCulvert.txt
  npc/re/instances/OldGlastHeim.txt
  npc/re/instances/WolfchevLaboratory.txt
  npc/re/instances/ghost_palace.txt
  npc/re/instances/octopus_cave.txt
  npc/re/instances/saras_memory.txt
  src/map/script.c
Labels: component:core:scriptengine, status:code-review, type:enhancement

#2079 Remove flag RTLD_DEEPBIND from dlopen.
  src/common/HPM.h
Labels: component:core:HPM, status:code-review

#2075 Fixed rodex_sendmail_acc script command and rodex examples
  doc/sample/npc_rodex.txt
  src/map/script.c
Labels: component:core:scriptengine, status:code-review, type:bug

#2106 Fix the shutdown callback (2015 regression)
  src/common/console.c
  src/common/core.c
Labels: component:core, severity:2-fair, type:bug

#2084 standardize the multi-form buildin definitions
  doc/script_commands.txt
Labels: codereview:accepted, component:documentation

#2077 Fix pre-increment / pre-decrement operator error
  npc/dev/test.txt
  src/map/script.c
Labels: component:core:scriptengine, status:code-review, type:bug

#2063 Implemented Pet Evolution and Pet Feeding
  conf/map/battle/feature.conf
  db/pre-re/pet_db.conf
  db/re/item_db.conf
  db/re/pet_db.conf
  sql-files/main.sql
  sql-files/upgrades/2018-06-05--12-02.sql
  sql-files/upgrades/index.txt
  src/char/int_pet.c
  src/common/mmo.h
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/clif.h
  src/map/packets.h
  src/map/packets_struct.h
  src/map/pet.c
  src/map/pet.h
  tools/petevolutionconverter.py
  tools/utils/common.py
Labels: component:core, mode:renewal

#2081 Adds setparam(), change optional param for readparam()
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, type:enhancement

#2097 Fix SC_INCATKRATE not working on monsters and Divest Weapon
  src/map/status.c
Labels: component:mechanics

#2100 Fix pincode bug
  src/char/pincode.c
Labels: status:code-review

#2095 Update packets up to 2018-06-27 and fix some existing packets
  src/char/char.c
  src/char/char.h
  src/char/pincode.c
  src/char/pincode.h
  src/common/HPMDataCheck.h
  src/common/mmo.h
  src/login/lclif.c
  src/login/lclif.p.h
  src/map/buyingstore.c
  src/map/buyingstore.h
  src/map/clif.c
  src/map/clif.h
  src/map/itemdb.c
  src/map/itemdb.h
  src/map/messages_main.h
  src/map/messages_re.h
  src/map/messages_zero.h
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_keys_zero.h
  src/map/packets_shuffle_main.h
  src/map/packets_shuffle_zero.h
  src/map/packets_struct.h
  src/map/pc.c
  src/map/script.c
  src/map/searchstore.c
  src/map/searchstore.h
  src/map/status.c
  src/map/vending.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_char.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_char.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: status:code-review
