Repository HerculesWS/Hercules, pull requests merged in 2018-07, with the labels that each got.

#2111 GitLab-CI fixes
  .gitlab-ci.yml
Labels: component:other

#2108 Mapif cleanup
  src/char/char.c
  src/char/char.h
  src/char/int_auction.c
  src/char/int_clan.c
  src/char/int_elemental.c
  src/char/int_elemental.h
  src/char/int_guild.c
  src/char/int_guild.h
  src/char/int_homun.c
  src/char/int_homun.h
  src/char/int_mail.c
  src/char/int_mail.h
  src/char/int_mercenary.c
  src/char/int_mercenary.h
  src/char/int_party.c
  src/char/int_party.h
  src/char/int_pet.c
  src/char/int_pet.h
  src/char/int_quest.c
  src/char/int_quest.h
  src/char/int_rodex.c
  src/char/int_rodex.h
  src/char/int_storage.c
  src/char/int_storage.h
  src/char/inter.c
  src/char/inter.h
  src/char/mapif.c
  src/char/mapif.h
  src/common/HPMDataCheck.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_char.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_char.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
Labels: component:core

#2086 Fix *queueopt documentation
  doc/script_commands.txt
  src/map/script.c
Labels: component:documentation

#2124 Guild add member fix
  src/char/int_guild.c
  src/char/int_guild.h
  src/char/mapif.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
Labels: severity:4-high, type:bug

#2134 Update int fields to using int32
  src/char/char.c
  src/char/int_pet.c
  src/char/int_pet.h
  src/char/int_rodex.c
  src/char/int_storage.c
  src/char/inter.c
  src/char/mapif.c
  src/common/mmo.h
  src/map/atcommand.c
  src/map/buyingstore.c
  src/map/buyingstore.h
  src/map/chrif.c
  src/map/clif.c
  src/map/clif.h
  src/map/intif.c
  src/map/intif.h
  src/map/itemdb.c
  src/map/itemdb.h
  src/map/map.c
  src/map/map.h
  src/map/mob.c
  src/map/mob.h
  src/map/npc.h
  src/map/packets_struct.h
  src/map/pc.c
  src/map/pc.h
  src/map/pet.c
  src/map/pet.h
  src/map/script.c
  src/map/script.h
  src/map/searchstore.c
  src/map/searchstore.h
  src/map/skill.c
  src/map/skill.h
  src/map/unit.h
  src/map/vending.c
  src/map/vending.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
  src/plugins/db2sql.c
Labels: status:code-review

#2088 Fixed monsters not disappearing from some clients upon death
  conf/map/battle/client.conf
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/clif.h
  src/map/map.h
Labels: component:core, type:bug

#2130 reload the const db on script reload
  db/constants.conf
  src/map/script.c
  src/map/script.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core:scriptengine, component:databases, type:enhancement

#2107 Questinfo System overhaul
  doc/script_commands.txt
  npc/re/jobs/novice/academy.txt
  npc/re/warps/cities/izlude.txt
  src/common/mmo.h
  src/map/clif.c
  src/map/homunculus.c
  src/map/instance.c
  src/map/map.c
  src/map/map.h
  src/map/pc.c
  src/map/quest.c
  src/map/quest.h
  src/map/script.c
Labels: status:code-review

#2136 Pet evolution bug fixes
  sql-files/main.sql
  sql-files/upgrades/2018-07-24--03-23.sql
  sql-files/upgrades/index.txt
  src/map/atcommand.c
  src/map/clif.c
  src/map/pet.c
  src/map/script.c
  src/map/skill.c
Labels: component:core, severity:2-fair, type:bug

#2153 Fix syntax error in sql update file 2018-07-24--03-23.sql
  sql-files/upgrades/2018-07-24--03-23.sql
Labels: status:code-review

#2147 Fix an issue that causes skill cooldowns to get stuck indefinitely
  src/map/pc.c
Labels: component:core, severity:5-critical, type:bug

#2156 remove specialeffect on first login from the novice academy script
  npc/re/jobs/novice/academy.txt
Labels: component:scripts

#2139 update packets up to 2018-07-18 and fix/update old packets
  src/common/HPMDataCheck.h
  src/map/atcommand.c
  src/map/chrif.c
  src/map/clif.c
  src/map/clif.h
  src/map/messages_main.h
  src/map/messages_re.h
  src/map/messages_zero.h
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_keys_zero.h
  src/map/packets_shuffle_main.h
  src/map/packets_shuffle_re.h
  src/map/packets_shuffle_zero.h
  src/map/packets_struct.h
  src/map/pc.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: status:code-review

#2148 Fix Venom Splasher consuming its gemstome requirement twice
  src/map/skill.c
Labels: component:core, component:mechanics:skills, severity:2-fair, type:bug

#2155 Add support for doram restriction in stylist shop
  db/stylist_db.conf
  src/map/clif.c
  src/map/clif.h
Labels: type:enhancement

#2157 correct sell item achievement being validated after item is deleted
  src/map/npc.c
Labels: component:core, type:bug

#2161 Fix achievement issues
  src/map/achievement.c
Labels: component:other, type:bug

#2090 Point all db\constant.conf to doc\constants.md
  doc/script_commands.txt
Labels: component:documentation

#2158 fix getd not setting the type to C_NAME for new variables
  src/map/script.c
Labels: component:core:scriptengine, type:bug

#2159 Set all fields to 0 in fake bl's.
  src/map/clif.c
  src/map/script.c
Labels: status:code-review
