Repository HerculesWS/Hercules, pull requests merged in 2018-05, with the labels that each got.

#2025 Comment out "MYPLUGINS ="
  src/plugins/Makefile.in
Labels: status:code-review

#2019 Convert mob_skill_db into libconf format
  db/mob_skill_db2.conf
  db/mob_skill_db2.txt
  db/pre-re/mob_skill_db.conf
  db/pre-re/mob_skill_db.txt
  db/re/mob_skill_db.conf
  db/re/mob_skill_db.txt
  src/map/mob.c
  src/map/mob.h
  src/map/script.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
  tools/mobskilldbconverter.py
  tools/utils/__init__.py
  tools/utils/common.py
  tools/utils/libconf.py
Labels: status:code-review, type:enhancement

#2028 Fix some possible buffer overflows.
  src/common/grfio.c
  src/common/sysinfo.c
  src/common/utils.c
  src/map/atcommand.c
  src/map/clif.c
  src/map/map.c
  src/map/map.h
Labels: status:code-review

#2029 Fix pincodes after commit 2a05dbfc2f62c6bbac7983dcec120502914567f1.
  src/char/pincode.c
Labels: status:code-review

#2030 Update packets.
  src/map/clif.c
  src/map/clif.h
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_keys_zero.h
  src/map/packets_shuffle_main.h
  src/map/packets_shuffle_zero.h
Labels: status:code-review

#2042 fix a wrong iterator used for mob skill db parsing
  src/map/mob.c
Labels: component:core, type:bug

#2043 Update packets
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_keys_zero.h
  src/map/packets_shuffle_main.h
  src/map/packets_shuffle_zero.h
Labels: status:code-review

#1851 Allow global unit lookups from scripts
  doc/script_commands.txt
  src/map/script.c
Labels: component:core, component:core:scriptengine, component:documentation, type:enhancement
