Repository HerculesWS/Hercules, pull requests merged in 2018-10, with the labels that each got.

#2227 only update zeny achievements and logs for non-zero transactions
  src/map/pc.c
Labels: type:bug

#2230 Fixes #2215: Turn effect_list.txt into effect_list.md
  doc/effect_list.md
  doc/effect_list.txt
Labels: component:documentation, type:enhancement

#2238 fix setting char/account variables of another player
  src/map/script.c
Labels: component:core:scriptengine, severity:4-high, type:bug

#2240 allow buildin_getd to work with constants and params
  npc/dev/test.txt
  src/map/script.c
Labels: component:core:scriptengine, type:enhancement

#2235 Fixed failed assertion in guild invite.
  src/map/guild.c
Labels: component:core, type:bug

#2239 Fixes an assertion error when sc_end is called for SC_BERSERK
  src/map/script.c
Labels: component:mechanics:skills, type:bug

#2253 Update Permission Documents
  README.md
  conf/groups.conf
  doc/permissions.md
  doc/permissions.txt
  doc/script_commands.txt
Labels: component:documentation, type:enhancement

#2172 Updated getiteminfo and setiteminfo.
  doc/sample/getiteminfo.txt
  doc/script_commands.txt
  npc/other/Global_Functions.txt
  src/map/script.c
  src/map/script.h
Labels: component:core:scriptengine, type:enhancement

#2234 Fixed Assertion Error when refine is failed
  src/map/achievement.c
Labels: component:core, type:bug

#2229 global_configuration.md
  doc/global_configuration.md
  doc/global_configuration.txt
Labels: component:documentation, type:enhancement

#2249 Add missing documentation for script command achievement_progress()
  doc/script_commands.txt
Labels: component:documentation, type:enhancement

#2279 deprecate buildin_prompt, bake it into buildin_select
  doc/script_commands.txt
  src/map/clif.c
  src/map/script.c
  src/map/script.h
Labels: component:core:scriptengine, component:documentation, type:enhancement
