Repository HerculesWS/Hercules, pull requests merged in 2018-02, with the labels that each got.

#1963 Add missing interfaces in login server. fix issue 1908
  Hercules.xcodeproj/project.pbxproj
  src/common/HPMDataCheck.h
  src/common/HPMSymbols.inc.h
  src/login/HPMlogin.c
  src/login/Makefile.in
  src/login/account.c
  src/login/account.h
  src/login/ipban.c
  src/login/ipban.h
  src/login/lclif.c
  src/login/login.c
  src/login/login.h
  src/login/loginlog.c
  src/login/loginlog.h
  src/plugins/HPMHooking.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_login.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_login.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_login.Hooks.inc
  src/plugins/HPMHooking/HPMHooking_login.sources.inc
  vcproj-11/login-server.vcxproj
  vcproj-11/login-server.vcxproj.filters
  vcproj-12/login-server.vcxproj
  vcproj-12/login-server.vcxproj.filters
  vcproj-14/login-server.vcxproj
  vcproj-14/login-server.vcxproj.filters
Labels: status:code-review

#1964 Clanfix
  Hercules.xcodeproj/project.pbxproj
  src/char/char.c
  src/char/int_clan.c
  src/common/mmo.h
  src/common/socket.c
  src/login/lclif.p.h
  src/map/atcommand.c
  src/map/battle.c
  src/map/battle.h
  src/map/clan.c
  src/map/clif.c
  src/map/clif.h
  src/map/intif.c
  src/map/pc.c
  src/map/rodex.c
  src/map/script.c
  src/map/skill.h
  src/map/status.c
  src/map/status.h
  src/map/unit.c
Labels: severity:1-trivial, type:bug

#1969 Update packets and keys tables up to 20180207.
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_keys_zero.h
  src/map/packets_shuffle_main.h
  src/map/packets_shuffle_zero.h
Labels: status:code-review

#1890 Overflow correction in visual function bg_message
  src/map/clif.c
Labels: codereview:accepted, component:client-interface, status:code-review

#1972 fix some clan issues
  conf/messages.conf
  src/map/atcommand.c
  src/map/map.c
Labels: component:core, severity:4-high, status:confirmed, type:bug

#1973 Fix unterminated strings in ZC_BATTLEFIELD_CHAT
  src/map/clif.c
Labels: component:core, severity:3-medium, type:bug

#1976 expose script_sprintf to plugins
  src/map/script.c
  src/map/script.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core:HPM, component:core:scriptengine, type:enhancement

#1975 Dont show password and pincode in @accinfo gm command.
  src/char/inter.c
Labels: status:code-review
