Repository HerculesWS/Hercules, pull requests merged in 2018-11, with the labels that each got.

#1857 mailmap update
  .mailmap
Labels: component:other, status:inprogress

#2105 break the loop in buildin_getunits when the max is reached
  src/map/map.c
  src/map/map.h
  src/map/script.c
Labels: component:core:scriptengine, severity:1-trivial, type:bug

#2304 add data_to_string()
  doc/script_commands.txt
  npc/dev/test.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2310 Update packets and messages up to 2018-11-07
  .travis.yml
  src/char/char.c
  src/map/clif.c
  src/map/messages_main.h
  src/map/messages_re.h
  src/map/messages_zero.h
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_keys_zero.h
  src/map/packets_shuffle_main.h
  src/map/packets_shuffle_re.h
  src/map/packets_shuffle_zero.h
  src/map/packets_struct.h
Labels: component:client-interface, type:enhancement

#2302 Proofread & edited CONTRIBUTING document
  CONTRIBUTING.md
Labels: component:documentation, type:enhancement

#2265 Fixed Logically Dead Code in status.c
  src/map/status.c
Labels: component:core, severity:1-trivial, status:code-review

#2319 Remove minicore
  Makefile.in
  configure
  configure.ac
  src/common/Makefile.in
  src/common/console.c
  src/common/core.c
  src/common/memmgr.h
  src/common/socket.c
  src/config/const.h
  src/tool/Makefile.in
Labels: component:other

#2259 Update Item Bonus Documentation
  doc/item_bonus.md
  doc/item_bonus.txt
Labels: component:documentation, type:enhancement

#2283 Fix a few typos in README
  README.md
Labels: component:documentation

#2247 fix map_zone_remove not actually removing flags
  src/map/map.c
  src/map/map.h
  src/map/npc.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core, severity:4-high, type:bug

#2320 Add relevant data to the charlog
  sql-files/main.sql
  src/char/char.c
Labels: component:SQL, type:enhancement

#2256 Update Quest Variables Documentation
  doc/quest_variables.md
  doc/quest_variables.txt
Labels: component:documentation, type:enhancement

#2255 Update Monster Modes Documentation
  doc/mob_db_mode_list.md
  doc/mob_db_mode_list.txt
  src/map/status.h
Labels: component:documentation, type:enhancement

#1215 Fixes #889 & #840
  conf/map/battle/client.conf
  src/map/atcommand.c
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/pc.c
  src/map/script.c
  src/map/skill.c
  src/map/status.c
  src/map/status.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:client-interface, type:enhancement

#1233 Fixed defense overflow exploit
  src/map/battle.c
  src/map/unit.c
Labels: component:mechanics

#2323 Fix clang-4.0 builds in gitlab-ci
  .gitlab-ci.yml
Labels: component:other, severity:1-trivial

#2322 Fix allychat leaveguild
  src/map/atcommand.c
  src/map/channel.c
  src/map/clif.c
  src/map/guild.c
  src/map/pc.c
  src/map/pc.h
  src/map/unit.c
Labels: component:core, severity:3-medium, type:bug
