Repository HerculesWS/Hercules, pull requests merged in 2018-08, with the labels that each got.

#2171 Fixed an achievement bug.
  src/map/achievement.c
Labels: component:core, severity:4-high, status:code-review, type:bug

#2154 improve is_function()
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2146 bake sprintf into debugmes
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2125 Adjust item_bonus.txt
  doc/item_bonus.txt
Labels: component:documentation

#2185 Add support for sak/ad client messages and show packet version and client type at server startup
  configure
  configure.ac
  src/common/console.c
  src/common/mmo.h
  src/map/Makefile.in
  src/map/messages.h
  src/map/messages_ad.h
  src/map/messages_sak.h
Labels: status:code-review

#2189 Change the language specification to C11 in the autoconf-based builds
  configure
  configure.ac
  src/common/cbasetypes.h
  src/common/strlib.h
  src/map/clif.c
  src/map/npc.c
Labels: type:enhancement

#2190 Packets updates/fixes
  src/map/clif.c
  src/map/clif.h
Labels: status:code-review

#2162 add atcommand_setzone, and fix #2133
  conf/messages.conf
  doc/atcommands.txt
  src/map/atcommand.c
  src/map/map.c
  src/map/map.h
  src/map/npc.c
Labels: component:documentation, component:other, type:bug, type:enhancement

#2164 always set the type to C_NAME when adding variables through script->add_str
  npc/dev/test.txt
  src/map/atcommand.c
  src/map/battleground.c
  src/map/channel.c
  src/map/clif.c
  src/map/duel.c
  src/map/intif.c
  src/map/mapreg_sql.c
  src/map/mob.c
  src/map/npc.c
  src/map/pc.c
  src/map/script.c
  src/map/script.h
  src/map/skill.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core, component:core:HPM, component:core:scriptengine, type:bug
