Repository HerculesWS/Hercules, pull requests merged in 2018-09, with the labels that each got.

#2203 Update Maps & NPC Consts Database
  conf/map/maps.conf
  db/constants.conf
  db/map_index.txt
  maps/pre-re/1@cor.mcache
  maps/pre-re/1@gl_prq.mcache
  maps/pre-re/1@os_a.mcache
  maps/pre-re/1@os_b.mcache
  maps/pre-re/1@rgsr.mcache
  maps/pre-re/gl_cas01_.mcache
  maps/pre-re/mag_dun03.mcache
  maps/pre-re/pub_cat.mcache
  maps/pre-re/rgsr_in.mcache
  maps/pre-re/sp_cor.mcache
  maps/pre-re/sp_os.mcache
  maps/pre-re/sp_rudus.mcache
  maps/pre-re/sp_rudus2.mcache
  maps/pre-re/sp_rudus3.mcache
  maps/re/1@cor.mcache
  maps/re/1@gl_prq.mcache
  maps/re/1@os_a.mcache
  maps/re/1@os_b.mcache
  maps/re/1@rgsr.mcache
  maps/re/gl_cas01_.mcache
  maps/re/mag_dun03.mcache
  maps/re/pub_cat.mcache
  maps/re/rgsr_in.mcache
  maps/re/sp_cor.mcache
  maps/re/sp_os.mcache
  maps/re/sp_rudus.mcache
  maps/re/sp_rudus2.mcache
  maps/re/sp_rudus3.mcache
  src/map/npc.h
Labels: component:databases

#2199 Update packets up to 2018-09-19
  .travis.yml
  configure
  configure.ac
  src/common/HPMDataCheck.h
  src/map/atcommand.c
  src/map/clif.c
  src/map/clif.h
  src/map/messages_main.h
  src/map/messages_re.h
  src/map/messages_zero.h
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_keys_zero.h
  src/map/packets_shuffle_main.h
  src/map/packets_shuffle_re.h
  src/map/packets_shuffle_zero.h
  src/map/packets_struct.h
  src/map/pc.c
  src/map/pet.c
  src/map/script.c
  src/map/skill.c
  src/map/storage.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: status:code-review

#2218 Fix wrong validation for quests in setquestinfo
  doc/script_commands.txt
  src/map/map.h
  src/map/quest.c
  src/map/script.c
Labels: type:bug

#2149 MobSkillDB to SQL conversion
  src/plugins/db2sql.c
Labels: component:core, type:enhancement
