Repository HerculesWS/Hercules, pull requests merged in 2018-04, with the labels that each got.

#1965 Implemented HatEffect
  db/constants.conf
  db/re/item_db.conf
  doc/script_commands.txt
  src/map/clif.c
  src/map/clif.h
  src/map/pc.c
  src/map/pc.h
  src/map/script.c
  src/map/unit.c
Labels: component:core, status:code-review

#1111 changed quest packets to structure form + some update
  src/map/clif.c
  src/map/clif.h
  src/map/packets_struct.h
  src/map/quest.c
Labels: component:client-interface, component:core, status:code-review, type:enhancement

#1986 Implemented login date for guild members.
  src/char/int_guild.c
  src/common/mmo.h
  src/map/clif.c
  src/map/guild.c
  src/map/guild.h
  src/map/intif.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: status:code-review

#2014 Update packets to 20180404 version
  src/char/char.c
  src/map/clif.c
  src/map/packets.h
  src/map/packets_keys_main.h
  src/map/packets_shuffle_main.h
Labels: status:code-review

#1868 Fixes #1806
  conf/map/battle/items.conf
  src/map/battle.c
  src/map/battle.h
  src/map/pc.c
Labels: codereview:accepted, status:code-review

#2000 Convert Pet db to Libconfig
  db/pet_db2.conf
  db/pet_db2.txt
  db/pre-re/item_db.conf
  db/pre-re/pet_db.conf
  db/pre-re/pet_db.txt
  db/re/pet_db.conf
  db/re/pet_db.txt
  src/map/pet.c
  src/map/pet.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
  tools/petdbconverter.py
Labels: component:databases, status:code-review

#1990 Implementation of Attendance system
  conf/map/battle/feature.conf
  conf/messages.conf
  db/attendance_db.conf
  sql-files/main.sql
  sql-files/upgrades/2018-03-10--04-06.sql
  sql-files/upgrades/index.txt
  src/char/char.c
  src/common/mmo.h
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/clif.h
  src/map/itemdb.c
  src/map/packets.h
  src/map/packets_struct.h
Labels: component:client-interface, status:code-review

#2006 Message Fixes
  conf/messages.conf
  npc/mapflag/noteleport.txt
  src/map/clif.c
  src/map/itemdb.h
  src/map/pc.c
  src/map/status.c
Labels: status:code-review

#2002 add missing homunculus autofeed update on change map
  src/map/clif.c
Labels: component:client-interface, status:code-review, type:bug

#2001 Added delay to tomb spawn
  conf/map/battle/monster.conf
  src/map/battle.c
  src/map/battle.h
  src/map/mob.c
  src/map/mob.h
  src/map/npc.h
Labels: component:mechanics, status:code-review, type:enhancement

#2009 Fix HPMHooking compilation when sprintf() is a macro
  src/map/script.c
  src/map/script.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core:HPM, type:bug

#1706 Fixes https://github.com/HerculesWS/Hercules/issues/680
  src/map/status.c
Labels: status:code-review

#2020 Enable some features for newer client versions
  conf/map/battle/feature.conf
  doc/item_db.txt
  src/map/clif.c
  src/map/packets_struct.h
Labels: component:client-interface

#2005 Allow guild skills cooldown to continue when logged out
  conf/map/battle/guild.conf
  src/map/battle.c
  src/map/guild.c
  src/map/skill.c
  src/map/skill.h
Labels: component:mechanics, type:enhancement

#2022 Refactor some functions to move MAPID_* related code into separate functions.
  src/map/pc.c
  src/map/pc.h
  src/map/status.c
  src/map/status.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: status:code-review

#2023 Remove stat server
  src/char/char.c
  src/char/char.h
  src/char/inter.c
  src/config/core.h
  src/map/battle.c
  src/map/chrif.c
  src/map/chrif.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_char.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_char.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core
