Repository HerculesWS/Hercules, pull requests merged in 2019-11, with the labels that each got.

#2574 Fix unintended nullpo errors
  src/map/mob.c
Labels: severity:4-high, type:bug

#2542 Update NPC locations
  npc/pre-re/quests/quests_payon.txt
  npc/pre-re/scripts.conf
  npc/quests/quests_payon.txt
  npc/re/cities/brasilis.txt
  npc/re/quests/quests_payon.txt
  npc/re/scripts.conf
  npc/warps/cities/lighthalzen.txt
  npc/warps/cities/yuno.txt
Labels: component:scripts, mode:pre-renewal, mode:renewal

#2566 add getguildinfo()
  doc/script_commands.txt
  npc/custom/etc/quest_warper.txt
  npc/custom/itembind.txt
  npc/custom/woe_controller.txt
  npc/events/gdevent_aru.txt
  npc/events/gdevent_sch.txt
  npc/events/god_se_festival.txt
  npc/events/nguild/nguild_ev_agit.txt
  npc/events/nguild/nguild_flags.txt
  npc/events/nguild/nguild_kafras.txt
  npc/events/nguild/nguild_managers.txt
  npc/kafras/functions_kafras.txt
  npc/quests/guildrelay.txt
  npc/quests/okolnir.txt
  npc/quests/seals/god_weapon_creation.txt
  npc/re/woe-fe/invest_main.txt
  npc/woe-fe/agit_controller.txt
  npc/woe-fe/agit_main.txt
  npc/woe-fe/aldeg_cas01.txt
  npc/woe-fe/aldeg_cas02.txt
  npc/woe-fe/aldeg_cas03.txt
  npc/woe-fe/aldeg_cas04.txt
  npc/woe-fe/aldeg_cas05.txt
  npc/woe-fe/gefg_cas01.txt
  npc/woe-fe/gefg_cas02.txt
  npc/woe-fe/gefg_cas03.txt
  npc/woe-fe/gefg_cas04.txt
  npc/woe-fe/gefg_cas05.txt
  npc/woe-fe/payg_cas01.txt
  npc/woe-fe/payg_cas02.txt
  npc/woe-fe/payg_cas03.txt
  npc/woe-fe/payg_cas04.txt
  npc/woe-fe/payg_cas05.txt
  npc/woe-fe/prtg_cas01.txt
  npc/woe-fe/prtg_cas02.txt
  npc/woe-fe/prtg_cas03.txt
  npc/woe-fe/prtg_cas04.txt
  npc/woe-fe/prtg_cas05.txt
  npc/woe-fe/trs_rp.txt
  npc/woe-se/agit_main_se.txt
  src/map/guild.c
  src/map/guild.h
  src/map/script.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core:scriptengine, component:documentation, component:scripts

#2564 Fix ud->target_to not being cleared appropriately
  src/map/unit.c
Labels: component:mechanics, severity:3-medium, status:code-review, type:bug
