Repository HerculesWS/Hercules, pull requests merged in 2019-10, with the labels that each got.

#2552 Removed jAthena 1082 legacy code related to Castle Defense Rate.
  conf/map/battle/guild.conf
  src/map/battle.c
  src/map/battle.h
  tools/configconverter.pl
Labels: component:mechanics

#2538 Fix a missing end in Slipslowrun NPC that allowed to reset the timer
  npc/other/arena/arena_party.txt
Labels: complexity: 0-trivial, component:scripts, severity:5-critical, type:bug

#2540 Fixed heap-buffer-overflow on npcshopdelitem
  src/map/script.c
Labels: component:core, severity:3-medium, type:bug

#2152 Moved hardcoded messages to conf
  conf/messages.conf
  src/map/battleground.c
  src/map/channel.c
  src/map/clif.c
  src/map/homunculus.c
  src/map/irc-bot.c
  src/map/mob.c
  src/map/pc.c
  src/map/skill.c
Labels: component:other, type:enhancement

#1935 Umbala Script Update:
  npc/quests/quests_umbala.txt
Labels: codereview:needsedits, component:scripts, type:bug

#2545 Update dropall atcommand
  conf/messages.conf
  src/map/atcommand.c
Labels: component:core, type:enhancement

#2543 Update Drooping Kitty item bonus
  db/pre-re/item_db.conf
  db/re/item_db.conf
Labels: component:databases, mode:pre-renewal, mode:renewal

#2544 Update Sense Skill - show 0 for negative values
  src/map/clif.c
Labels: component:mechanics:skills

#2549 Fix HP bar not showing when unhiding in a party
  src/map/status.c
Labels: complexity: 1-straightforward, component:mechanics, severity:1-trivial, status:code-review, type:bug

#2553 Correct Magnum Break delay
  db/pre-re/skill_db.conf
  db/re/skill_db.conf
  src/map/skill.c
Labels: component:mechanics:skills, status:code-review, type:bug

#2555 Fixes close merchant vending
  src/map/clif.c
Labels: component:core, type:bug

#2556 Homunculus skill fixes
  src/map/skill.c
  src/map/unit.c
Labels: component:mechanics:skills, severity:3-medium, status:code-review, type:bug

#2561 Make slave mobs react to master's chase target
  conf/map/battle/monster.conf
  src/map/battle.c
  src/map/battle.h
  src/map/mob.c
  src/map/mob.h
Labels: component:mechanics, severity:3-medium, status:code-review, type:bug

#2550 Fix aggressive ranged mobs not attacking from above a cliff
  src/map/mob.c
Labels: component:mechanics, severity:3-medium, status:code-review, type:bug
