Repository HerculesWS/Hercules, pull requests merged in 2019-04, with the labels that each got.

#2170 Added configuration to enable/disable achievement system
  conf/map/battle/feature.conf
  src/map/achievement.c
  src/map/battle.c
  src/map/battle.h
Labels: component:other, status:code-review

#2401 Expanded getinventorylist:
  doc/script_commands.txt
  src/map/script.c
Labels: component:core, component:core:scriptengine, component:documentation, type:enhancement

#2388 Add optional parameter for *gettimestr
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2398 Deprecate *petstat and add CONSTANTS to *getpetinfo
  db/constants.conf
  doc/script_commands.txt
  src/map/script.c
  src/map/script.h
Labels: component:core:scriptengine, component:documentation

#2367 Add new server define constant MAX_ITEM_ID
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, type:enhancement

#2402 Fix @bodystyle crash client
  src/map/pc.c
Labels: component:core, status:code-review, type:bug

#2442 Fix issue #1955
  npc/custom/events/mushroom_event.txt
Labels: component:scripts

#2443 Disable chatroom creation if cell_chknochat
  src/map/chat.c
Labels: component:core

#2440 Added *consolemes script command
  doc/script_commands.txt
  npc/custom/etc/quest_warper.txt
  npc/custom/quests/quest_shop.txt
  npc/custom/quests/thq/THQS_TTShop.txt
  npc/dev/test.txt
  npc/woe-fe/agit_main.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2439 Update dropall atcommand drop item based on type.
  conf/messages.conf
  doc/atcommands.txt
  src/map/atcommand.c
  src/map/atcommand.h
Labels: component:documentation, type:enhancement
