Repository HerculesWS/Hercules, pull requests merged in 2019-09, with the labels that each got.

#2515 Update Siegfried Tokens support.
  db/pre-re/item_chain.conf
  db/re/item_chain.conf
  src/map/clif.c
  src/map/itemdb.c
  src/map/itemdb.h
  src/map/pc.c
  src/map/pc.h
Labels: component:core, status:confirmed, type:bug

#2533 Fix two examples in scripting documentation
  doc/script_commands.txt
Labels: complexity: 0-trivial, component:documentation

#2527 Corrected KVM Logistic Officer item ID
  npc/battleground/kvm/kvm_item_pay.txt
  npc/custom/battleground/bg_kvm01.txt
  npc/custom/battleground/bg_kvm02.txt
  npc/custom/battleground/bg_kvm03.txt
Labels: component:scripts, type:bug

#2529 Convert item combo db to use libconfig
  db/pre-re/item_combo_db.conf
  db/pre-re/item_combo_db.txt
  db/re/item_combo_db.conf
  db/re/item_combo_db.txt
  src/map/itemdb.c
  src/map/itemdb.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
  tools/itemcombodbconverter.py
  tools/utils/common.py
Labels: component:core, component:databases, type:enhancement

#2336 Implementation of LapineDdukDdak System
  db/pre-re/item_db.conf
  db/pre-re/item_lapineddukddak.conf
  db/re/item_db.conf
  db/re/item_lapineddukddak.conf
  doc/script_commands.txt
  src/map/clif.c
  src/map/clif.h
  src/map/itemdb.c
  src/map/itemdb.h
  src/map/packets.h
  src/map/packets_struct.h
  src/map/pc.h
  src/map/script.c
  src/map/script.h
Labels: status:code-review

#2532 Add Library Mistake Quest
  db/quest_db.conf
  db/re/mob_db.conf
  npc/jobs/valkyrie.txt
  npc/re/mobs/fields/yuno.txt
Labels: component:databases, component:scripts, mode:renewal, status:confirmed
