Repository HerculesWS/Hercules, pull requests merged in 2019-07, with the labels that each got.

#2332 Fix sealed bapho problem
  npc/instances/SealedShrine.txt
Labels: component:scripts

#2499 Disable refresh atcommand when talk with NPC.
  src/map/atcommand.c
Labels: component:core

#2500 Update @reloadmobdb to update living mobs
  src/map/mob.c
  src/map/mob.h
Labels: component:core

#2502 Fix family check and EXP bug
  src/char/char.c
Labels: component:core

#2503 Fix Wounded Morocc Cooldown
  npc/quests/quests_morocc.txt
Labels: component:scripts

#2504 Update refine atcommand
  conf/messages.conf
  doc/atcommands.txt
  src/map/atcommand.c
  src/map/atcommand.h
Labels: component:core, component:documentation, type:enhancement

#2505 Added battle config autoloot_adjust
  conf/map/battle/drops.conf
  src/map/battle.c
  src/map/battle.h
  src/map/mob.c
Labels: component:core, mode:renewal, type:enhancement

#2508 Update script command isequipped count
  src/map/script.c
Labels: component:core:scriptengine

#2509 Update Runestones stack limit
  db/re/item_db.conf
Labels: component:databases, mode:renewal

#2510 Update mob_db - DamageTakenRate field
  db/constants.conf
  db/mob_db2.conf
  db/pre-re/mob_db.conf
  db/re/mob_db.conf
  doc/script_commands.txt
  src/map/battle.c
  src/map/mob.c
  src/map/mob.h
  src/map/script.c
  src/map/script.h
  src/map/skill.c
Labels: component:core:scriptengine, component:databases, component:documentation, mode:renewal

#2507 Update Homunculus obtain EXP from master
  conf/map/battle/homunc.conf
  src/map/battle.c
  src/map/battle.h
  src/map/homunculus.c
  src/map/pc.c
Labels: component:core
