Repository HerculesWS/Hercules, pull requests merged in 2019-03, with the labels that each got.

#2390 Add MOB_CLONE_START & MOB_CLONE_END to server defined constants
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2360 Added missing return on F_GetTradeRestriction
  npc/other/Global_Functions.txt
Labels: component:scripts, type:bug

#2381 Add missing documentation for disable battleground respawn
  doc/script_commands.txt
  src/map/script.c
Labels: component:documentation

#2397 Add constants and MERCINFO_GID to *getmercinfo script command
  doc/script_commands.txt
  npc/re/jobs/3-1/archbishop.txt
  npc/re/jobs/3-1/ranger.txt
  npc/re/quests/eden/eden_tutorial.txt
  src/map/script.c
  src/map/script.h
Labels: component:core:scriptengine, type:enhancement

#2396 * Add *mobattached and *killmonstergid script command
  doc/script_commands.txt
  npc/quests/quests_rachel.txt
  src/map/script.c
Labels: codereview:accepted, component:core:scriptengine, component:documentation, type:enhancement

#2391 setunitdata/getunitdata clean up. Phase 1
  db/constants.conf
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:bug

#2399 Fix *needed_status_point not support <char_id>
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation
