Repository HerculesWS/Hercules, pull requests merged in 2019-05, with the labels that each got.

#2309 Support for monster drops with Random Options
  conf/map/battle/drops.conf
  db/mob_db2.conf
  db/option_drop_groups.conf
  db/pre-re/mob_db.conf
  db/re/mob_db.conf
  doc/mob_db.txt
  doc/option_drop_group.md
  src/common/HPMDataCheck.h
  src/map/battle.c
  src/map/battle.h
  src/map/mob.c
  src/map/mob.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:databases, component:mechanics, status:code-review

#2426 Expand *getinventorylist() script command - favorite field
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation

#2068 Add F_MesItemInfo function to show item name with description link
  doc/script_commands.txt
  npc/other/Global_Functions.txt
  npc/re/instances/OldGlastHeim.txt
Labels: component:scripts, status:code-review, type:enhancement

#2232 Added option to make hunter traps invisible
  conf/map/battle/skill.conf
  db/pre-re/skill_db.conf
  db/re/skill_db.conf
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/skill.c
  src/map/skill.h
Labels: component:databases, component:mechanics:skills, type:enhancement

#2453 Update unitwarp script command.
  src/map/unit.c
Labels: component:core:scriptengine

#2483 Update item_db - Stat Reduction Potions
  db/re/item_db.conf
Labels: component:databases, mode:renewal
