Repository HerculesWS/Hercules, pull requests merged in 2019-02, with the labels that each got.

#2151 Updated message on char-server
  src/char/char.c
  src/login/login.c
Labels: component:other, type:enhancement

#2307 Added countnameditem script command.
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#1656 Fixes #1655 - Fix to Sura Job Change Quest get stuck after first attemp.
  npc/re/jobs/3-2/sura.txt
Labels: codereview:accepted, complexity: 1-straightforward, component:scripts
