Repository HerculesWS/Hercules, pull requests merged in 2019-06, with the labels that each got.

#2433 Move questinfo data from map to npc_data
  src/common/HPMDataCheck.h
  src/map/clif.c
  src/map/instance.c
  src/map/map.c
  src/map/map.h
  src/map/npc.c
  src/map/npc.h
  src/map/quest.c
  src/map/quest.h
  src/map/script.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: status:code-review

#2375 Allow *input script command to support negative input
  conf/map/script.conf
  src/map/clif.c
  src/map/pc.h
  src/map/script.c
Labels: component:core:scriptengine, type:bug

#2477 Fix *failedremovecards script command.
  src/map/script.c
Labels: component:core:scriptengine

#2474 Update *getmapinfo script command.
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation

#2472 Add *cap_value script command
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation

#2471 Add *mesclear script command.
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation

#2456 Update Byorgue summon slave delay
  db/pre-re/mob_skill_db.conf
Labels: component:databases, mode:pre-renewal

#2430 Fix map-crash when floating npc use *npcspeed script command
  src/map/script.c
Labels: component:core:scriptengine

#2380 Standardize to "all" in script commands
  doc/script_commands.txt
  npc/custom/events/mushroom_event.txt
  npc/re/instances/ghost_palace.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation

#2222 Simplify windows installation
  README.md
  mariadb.bat
  tools/install_mariadb.bat
  tools/setup_mariadb.ps1
Labels: component:SQL, component:documentation, component:other, type:enhancement

#2394 Adds BUILDIN(delitemidx), which deletes an item at the given index.
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2457 Update NPC scripts
  npc/jobs/1-1e/ninja.txt
  npc/quests/quests_nameless.txt
  npc/quests/quests_prontera.txt
  npc/re/jobs/2e/kagerou_oboro.txt
  npc/re/merchants/renters.txt
Labels: component:scripts, mode:pre-renewal, mode:renewal

#2374 standardize script commands to small letters
  doc/script_commands.txt
  npc/other/inventory_expansion.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, component:scripts

#2290 Adds buildin_getguildonline.
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation

#2357 Update stylist.txt
  npc/custom/stylist.txt
Labels: component:scripts, type:enhancement

#2427 Add *setfavoriteitemidx & *autofavoriteitem script commands - alter item favorite state
  doc/script_commands.txt
  src/map/itemdb.h
  src/map/pc.c
  src/map/script.c
Labels: component:core:scriptengine, component:documentation

#2343 Added missing equipment
  npc/re/merchants/enchan_mora.txt
Labels: component:scripts, mode:renewal

#2476 Add new atcommand *reloadnpc
  doc/atcommands.txt
  src/map/atcommand.c
Labels: component:core, component:documentation

#2487 Add identify/identifyidx script commands and identifyall atcommand
  doc/atcommands.txt
  doc/script_commands.txt
  src/map/atcommand.c
  src/map/script.c
Labels: component:core:scriptengine, component:documentation
