Repository HerculesWS/Hercules, pull requests merged in 2020-02, with the labels that each got.

#2601 Fix C4018 compiler warning in src\char\int_party.c.
  src/char/int_party.c
  src/char/int_party.h
  src/common/mmo.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
Labels: complexity: 0-trivial, component:core, status:code-review

#1495 Update Duel System Cooldown
  conf/map/battle/misc.conf
  conf/messages.conf
  src/map/atcommand.c
  src/map/duel.c
  src/map/duel.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: codereview:accepted, component:core, type:enhancement

#2248 Minor fixes to Asura Strike
  src/map/skill.c
Labels: codereview:accepted, component:mechanics:skills

#2614 Updated items which used SC_ARMORPROPERTY or SC_ARMOR_RESIST.
  db/pre-re/item_db.conf
  db/re/item_db.conf
Labels: component:databases, mode:pre-renewal, mode:renewal, status:code-review

#2590 Change unload NPC behavior to kill mobs that were spawned by unloaded NPC (non-permanent monster spawns) [Issue #2530]
  conf/messages.conf
  doc/atcommands.txt
  doc/script_commands.txt
  src/common/utils.c
  src/common/utils.h
  src/map/atcommand.c
  src/map/atcommand.h
  src/map/clif.c
  src/map/instance.c
  src/map/map.c
  src/map/mob.c
  src/map/mob.h
  src/map/npc.c
  src/map/npc.h
  src/map/script.c
  src/map/skill.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core, component:core:scriptengine, component:documentation, status:code-review

#2618 Updated PR_STRECOVERY to only cure status effects if defence element is not Undead.
  src/map/skill.c
Labels: codereview:accepted, component:mechanics:skills, type:bug

#2621 Added Rebellion Job Quest
  db/quest_db.conf
  db/re/item_db.conf
  db/re/mob_db.conf
  npc/re/jobs/2e/rebellion.txt
  npc/re/scripts_jobs.conf
Labels: component:scripts, mode:renewal, type:enhancement

#2617 Added an initial dmg_taken_rate value to clone spawns.
  src/map/mob.c
Labels: component:core, status:code-review, type:bug

#2619 Crash fixes
  src/map/map.c
  src/map/script.c
Labels: component:core, type:bug

#2622 Make mob DB field ViewData->HairStyleId defaulting to 1 instead of 0.
  db/pre-re/mob_db.conf
  db/re/mob_db.conf
  doc/mob_db.txt
  src/map/mob.c
Labels: component:databases, component:documentation, status:code-review

#2620 Updated mobdbconverter tools
  tools/mobdbconverter.py
Labels: component:other, type:enhancement

#2623 Fix W_RIFLE damage calculation being too low than intended
  src/map/battle.c
Labels: complexity: 1-straightforward, component:mechanics, mode:pre-renewal, severity:3-medium, type:bug

#2624 Merge pre-RE/RE case SP_VARCASTRATE in pc_readparam() function
  src/map/pc.c
Labels: component:core, status:code-review, type:enhancement

#2626 Fix Homunculi being partially vaporized.
  src/map/homunculus.c
Labels: component:mechanics, severity:3-medium, type:bug

#2627 Change NPC ID validation in npc_scriptcont()
  src/map/npc.c
Labels: component:core:scriptengine, status:code-review, type:bug

#2616 Modified itemskill() script command to be usable like AEGIS' SkillToMe command.
  db/pre-re/item_db.conf
  db/re/item_db.conf
  doc/script_commands.txt
  src/common/HPMDataCheck.h
  src/map/clif.c
  src/map/itemdb.h
  src/map/packets_struct.h
  src/map/pc.c
  src/map/pc.h
  src/map/script.c
  src/map/script.h
  src/map/skill.c
  src/map/skill.h
  src/map/unit.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core:scriptengine, component:databases, component:documentation, component:mechanics, status:code-review
