Repository HerculesWS/Hercules, pull requests merged in 2020-01, with the labels that each got.

#2285 Adds buildin_resetfeel, buildin_resethate and acmd_hatereset.
  conf/map/help.txt
  conf/messages.conf
  doc/atcommands.txt
  doc/script_commands.txt
  src/map/atcommand.c
  src/map/script.c
Labels: codereview:accepted, component:core:scriptengine, component:documentation

#2606 Adding PCBLOCK_NPC to setpcblock script command
  doc/constants.md
  doc/script_commands.txt
  src/map/clif.c
  src/map/pc.h
  src/map/script.c
  src/map/script.h
  src/map/unit.c
Labels: codereview:accepted, component:core:scriptengine, type:enhancement

#2604 Add flag to ignore mapflag restrictions in warpparty() and warpguild() script commands.
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, status:code-review

#2266 Fixed a condition in RoDEX attachment
  src/map/clif.c
Labels: component:core, severity:2-fair, status:code-review
