Repository HerculesWS/Hercules, pull requests merged in 2020-05, with the labels that each got.

#2686 Fix status changes falsely being recognized as unknown
  src/map/mob.c
  src/map/skill.c
  src/map/status.c
Labels: component:mechanics, status:code-review, type:bug

#2687 Fix unhiding while being disguised and when using @option 0
  src/map/atcommand.c
  src/map/pc.c
  src/map/pc.h
Labels: component:client-interface, status:code-review, type:bug

#2689 Renewal pet DB update
  db/mob_db2.conf
  db/pet_db2.conf
  db/pre-re/mob_db.conf
  db/re/item_combo_db.conf
  db/re/item_db.conf
  db/re/mob_db.conf
  db/re/mob_skill_db.conf
  db/re/pet_db.conf
  src/map/mob.c
Labels: component:databases, mode:renewal, status:code-review, type:enhancement

#2690 Fix usage of *= operator
  src/map/map.c
  src/map/mob.c
  src/map/pc.c
  src/map/pet.c
  src/map/skill.c
Labels: component:core, severity:3-medium, status:code-review, type:bug

#2693 Fix conditions for calling pet_ai_sub_hard()
  src/map/pet.c
Labels: component:core, status:code-review, type:bug

#2691 Extend and clean up monster skill DB code
  db/mob_skill_db2.conf
  db/pre-re/mob_skill_db.conf
  db/re/mob_skill_db.conf
  src/common/cbasetypes.h
  src/map/mob.c
  src/map/mob.h
  src/map/script.c
  src/map/unit.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core, component:databases, component:mechanics:skills, status:code-review, type:enhancement

#2680 New Doc: mob_skill_db.conf
  doc/mob_skill_db.md
Labels: component:documentation, status:code-review

#2696 Make SC_NOCHAT gets affected by battle config changes
  src/map/pc.h
  src/map/status.c
Labels: component:core, status:code-review, type:bug

#2062 Fix *atcommand cannot be use when PCBLOCK_COMMANDS is true
  src/map/atcommand.c
  src/map/script.c
Labels: component:core:scriptengine, type:bug

#2710 Fix skill idx
  src/char/char.c
  src/map/pc.c
  src/map/skill.c
  src/map/skill.h
Labels: component:core, severity:4-high, status:code-review, type:bug

#1304 Fix some skills bugs
  src/map/battle.c
  src/map/skill.c
Labels: component:mechanics:skills, status:code-review, type:bug

#2188 Adds 'cell_noskill' which blocks skill usage.
  db/constants.conf
  doc/constants.md
  src/map/map.c
  src/map/map.h
  src/map/skill.c
Labels: component:databases, component:mechanics:skills, type:enhancement

#2705 Cap string variable value length and unify corresponding SQL columns size
  doc/script_commands.txt
  sql-files/main.sql
  sql-files/upgrades/2020-05-01--04-44.sql
  sql-files/upgrades/index.txt
  src/char/char.c
  src/char/inter.c
  src/char/mapif.c
  src/common/mmo.h
  src/login/account.c
  src/map/atcommand.c
  src/map/clif.c
  src/map/intif.c
  src/map/mapreg_sql.c
  src/map/npc_chat.c
  src/map/script.c
  src/map/script.h
Labels: component:core:scriptengine, component:databases, status:code-review, type:enhancement

#2708 Implement SC_RESIST_PROPERTY_* and icon display for SC_ARMOR_RESIST
  db/pre-re/item_db.conf
  db/re/item_db.conf
  src/map/status.c
Labels: component:databases, component:mechanics, status:code-review, type:bug

#2142 allow local NPC functions to be public or private
  conf/map/script.conf
  doc/script_commands.txt
  npc/dev/test.txt
  src/map/map.h
  src/map/npc.c
  src/map/npc.h
  src/map/script.c
  src/map/script.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core, component:core:scriptengine, type:bug, type:enhancement

#2698 Fixed lost puppies quest
  npc/re/quests/quests_brasilis.txt
Labels: codereview:accepted, component:scripts, mode:renewal, type:bug

#2714 Secure gender changing
  src/map/chrif.c
Labels: component:mechanics, status:code-review, type:bug

#2720 Split mapreg table and refactor mapreg code
  conf/common/inter-server.conf
  sql-files/main.sql
  sql-files/upgrades/2020-05-10--23-11.sql
  sql-files/upgrades/index.txt
  src/map/map.c
  src/map/mapreg.h
  src/map/mapreg_sql.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:SQL, component:core, status:code-review, type:enhancement

#2721 Enable receiving not NULL terminated whisper names with a length of 24 characters
  src/map/clif.c
Labels: component:client-interface, status:code-review, type:enhancement

#2733 Add MSC_MAGICATTACKED cast condition for monster skills
  doc/mob_skill_db.md
  src/map/mob.c
  src/map/mob.h
  src/map/script.c
Labels: component:documentation, component:mechanics:skills, status:code-review, type:enhancement

#2736 Remove misleading debug code for nonexistent skill unit group when ending SC_DANCING
  src/map/battle.c
  src/map/guild.c
  src/map/pc.h
  src/map/skill.c
  src/map/skill.h
  src/map/status.c
  src/map/status.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core, status:code-review, type:bug

#2729 Add nicks and emails from all commits into AUTHORS file
  .mailmap
  AUTHORS
  tools/authors.sh
Labels: codereview:accepted, component:other, type:enhancement

#2739 Update drop chances of Black and White Wing Suits
  db/re/mob_db.conf
Labels: component:databases, mode:renewal, status:code-review, type:bug

#2699 Enable multiple itemskill() calls per item
  src/map/battle.c
  src/map/clif.c
  src/map/pc.c
  src/map/pc.h
  src/map/script.c
  src/map/skill.c
  src/map/status.c
  src/map/unit.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:mechanics:skills, status:code-review, type:bug
