Repository HerculesWS/Hercules, pull requests merged in 2020-06, with the labels that each got.

#2731 Extend and clean up skill DB code
  db/pre-re/skill_db.conf
  db/re/skill_db.conf
  src/map/battle.c
  src/map/clif.c
  src/map/itemdb.h
  src/map/map.c
  src/map/mob.c
  src/map/npc.c
  src/map/skill.c
  src/map/skill.h
  src/map/status.c
  src/map/unit.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:databases, component:mechanics:skills, status:code-review, type:enhancement

#2671 add support for binary and octal number literals
  .gitattributes
  3rdparty/libconfig/extra/.gitignore
  3rdparty/libconfig/extra/gen/Makefile
  3rdparty/libconfig/extra/gen/clangwarnings.patch
  3rdparty/libconfig/extra/gen/grammar.y
  3rdparty/libconfig/extra/gen/scanner.l
  3rdparty/libconfig/grammar.c
  3rdparty/libconfig/grammar.h
  3rdparty/libconfig/libconfig.c
  3rdparty/libconfig/libconfig.h
  3rdparty/libconfig/scanner.c
  3rdparty/libconfig/scanner.h
  3rdparty/libconfig/wincompat.h
  db/constants.conf
  doc/script_commands.txt
  npc/dev/test.txt
  src/common/cbasetypes.h
  src/map/script.c
  tools/utils/libconf.py
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2220 New configure options
  src/common/mmo.h
Labels: component:core, status:code-review, type:enhancement

#2718 Add/extend battle flags to enable item/skill usage while interacting with NPC
  conf/map/battle/items.conf
  conf/map/battle/skill.conf
  doc/script_commands.txt
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/pc.c
  src/map/pc.h
  src/map/script.c
  src/map/skill.h
Labels: component:mechanics, mode:pre-renewal, status:code-review, type:bug

#2723 Replace NULL pointer report with returning error code in unit_steptimer()
  src/map/unit.c
Labels: component:core, status:code-review, type:bug

#2734 Fix left shift of negative value for GN_CRAZYWEED_ATK
  src/map/skill.c
Labels: component:mechanics:skills, status:code-review, type:bug

#2744 Save a pet's rename flag when returning it to its egg
  src/map/pet.c
Labels: component:core, status:code-review, type:bug

#2746 Fix an issue regarding using items when the storage is open.
  src/map/pc.c
Labels: codereview:accepted, component:mechanics, type:bug

#2752 Player always faces north when warped.
  conf/map/battle/player.conf
Labels: codereview:accepted, component:configuration, type:bug

#2754 Make mineffect flag not being affected by sd->state.lesseffect in clif_maptypeproperty2()
  src/map/clif.c
Labels: component:client-interface, status:code-review, type:bug

#2758 Add loudhailer() script command
  db/pre-re/item_db.conf
  db/re/item_db.conf
  doc/script_commands.txt
  src/map/clif.c
  src/map/clif.h
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, status:code-review, type:bug

#2745 Prevent unequipping items on login before calculating the character's status data
  src/map/clif.c
  src/map/pc.c
Labels: component:core, status:code-review, type:bug

#2747 In official, novice don't have job level stat bonus
  db/job_db2.txt
Labels: codereview:accepted, component:databases, status:confirmed, type:bug

#2732 Update instancing window display and documentation of instance_create() script command
  doc/script_commands.txt
  src/map/clif.c
  src/map/guild.c
  src/map/instance.c
  src/map/party.c
Labels: component:documentation, status:code-review, type:enhancement

#2755 Added configuration on allowing actions on player when dead.
  conf/map/battle/player.conf
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/pc.h
  src/map/script.c
Labels: component:configuration, component:core, component:mechanics, type:enhancement

#2762 Fix updating SQL data when removing party member or options are changed in inter_party_check_lv()
  src/char/int_party.c
Labels: component:core, status:code-review, type:bug

#2712 Fix condition for deleting skill units when unloading NPC
  src/map/skill.c
Labels: component:core, status:code-review, type:bug

#2774 Fix required item index selection for various skills
  src/map/skill.c
  src/map/skill.h
Labels: component:mechanics:skills, severity:5-critical, status:code-review, type:bug

#2781 Add some pet features and minor pet code clean up
  conf/map/battle/pet.conf
  src/map/atcommand.c
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/pc.c
  src/map/pc.h
  src/map/pet.c
  src/map/pet.h
  src/map/script.c
Labels: component:configuration, component:mechanics, status:code-review, type:enhancement

#2765 Fix wrong comment in attr_fix.txt
  db/pre-re/attr_fix.txt
  db/re/attr_fix.txt
Labels: component:databases, status:code-review, type:bug

#2775 Fix Megaphone behaviour
  src/map/buyingstore.c
  src/map/clif.c
  src/map/itemdb.h
  src/map/mail.c
  src/map/pc.c
  src/map/pc.h
  src/map/rodex.c
  src/map/script.c
  src/map/trade.c
  src/map/vending.c
Labels: component:mechanics, status:code-review, type:bug

#2757 Adjust server messages on login and map change
  conf/map/battle/client.conf
  conf/map/battle/guild.conf
  conf/map/battle/party.conf
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/clif.h
  src/map/packets_struct.h
  src/map/party.c
  src/map/party.h
  src/map/pc.c
Labels: component:client-interface, component:configuration, component:core, status:code-review, status:inprogress, type:enhancement

#2784 Enlarge field size of npc_item_flag in struct script_state according to possible values
  src/map/battle.c
  src/map/script.h
Labels: component:core, component:core:scriptengine, status:code-review, type:bug

#2756 Storage now closes when using teleport skill.
  conf/map/battle/skill.conf
  src/map/battle.c
  src/map/battle.h
  src/map/skill.c
Labels: component:configuration, component:core, component:mechanics, type:bug, type:enhancement

#2782 Fix npc selling behavior if price is over INT_MAX.
  src/map/npc.c
Labels: component:core:scriptengine, status:code-review, type:enhancement

#2786 Pass timer data when re-applying status icons upon spawning character
  src/map/clif.c
Labels: component:client-interface, component:core, status:code-review, type:bug
