Repository HerculesWS/Hercules, pull requests merged in 2020-03, with the labels that each got.

#2643 Missing get_index call in Skill2SCTable.
  src/map/status.c
Labels: codereview:accepted, component:core, severity:5-critical, type:bug

#2650 Added Item Bound Type constants
  doc/script_commands.txt
  npc/custom/itembind.txt
  src/map/script.c
Labels: component:documentation, component:scripts, type:enhancement

#2612 Fix Basilica unintentionally restraining boss mobs
  src/map/battle.c
Labels: complexity: 1-straightforward, component:mechanics:skills, severity:4-high

#2634 Update items 12459-12465
  db/pre-re/item_db.conf
  db/re/item_db.conf
Labels: component:databases, status:code-review

#2546 Refactor unit.c - Part I
  src/map/atcommand.c
  src/map/battle.c
  src/map/clif.c
  src/map/elemental.c
  src/map/map.c
  src/map/map.h
  src/map/mob.c
  src/map/npc.c
  src/map/npc.h
  src/map/pet.c
  src/map/script.c
  src/map/skill.c
  src/map/skill.h
  src/map/unit.c
  src/map/unit.h
  src/map/unitdefines.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
  tools/HPMHookGen/HPMHookGen.pl
Labels: complexity: 3-challenging, component:core, component:documentation, status:code-review, type:enhancement

#2628 Add unitiswalking() script command
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, status:code-review, type:enhancement

#2633 Add new return values to pc_setpos() function
  src/map/pc.c
Labels: component:core, status:code-review

#2638 Increase MAX_MOB_LIST_PER_MAP to 115 in pre-RE mode
  src/map/mapdefines.h
Labels: component:core, mode:pre-renewal, status:code-review

#2639 Extend getiteminfo() script command
  doc/script_commands.txt
  src/map/script.c
  src/map/script.h
Labels: component:core:scriptengine, component:documentation, status:code-review, type:enhancement

#2642 Fix (un)equip script execution for map zone restrcited items
  src/map/clif.c
  src/map/pc.c
Labels: component:core, status:code-review, type:bug

#2648 Fix itemskill() script command
  db/pre-re/item_db.conf
  db/pre-re/skill_db.conf
  db/re/item_db.conf
  db/re/skill_db.conf
  doc/script_commands.txt
  src/map/pc.c
  src/map/pc.h
  src/map/script.c
  src/map/script.h
  src/map/skill.c
  src/map/unit.c
Labels: component:core:scriptengine, component:databases, severity:4-high, status:code-review, type:bug

#2651 Item with favorite flag can't sell to NPC.
  src/map/clif.c
Labels: component:core

#2659 Fix wrong return-value on success by unit->walktobl
  src/map/unit.c
Labels: severity:5-critical, type:bug

#2664 Fix mobs get stuck when trying to loot
  src/map/unit.c
Labels: component:core, severity:4-high, status:code-review, type:bug
