Repository HerculesWS/Hercules, pull requests merged in 2020-07, with the labels that each got.

#2797 Dokebi Battle Quest bugfix and exploit patch
  npc/quests/quests_amatsu.txt
Labels: complexity: 2-moderate, component:scripts, severity:5-critical, type:bug

#2796 Fix @changesex not saving new gender to SQL DB
  src/char/char.c
Labels: component:core, status:code-review, status:needs-squashing, type:bug

#2792 Fix Moscovia quests getting stuck in infinite loop
  npc/quests/quests_moscovia.txt
Labels: component:scripts, status:code-review, type:bug

#2791 Prevent overflow when using gettimetick(0)
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, status:code-review, type:bug

#2794 Update NPC OnSellitem Array List
  doc/script_commands.txt
  src/map/npc.c
Labels: component:core:scriptengine, component:documentation

#2652 Add NoPet mapflag
  conf/map/battle/pet.conf
  conf/messages.conf
  db/constants.conf
  npc/mapflag/nopet.txt
  npc/scripts_mapflags.conf
  src/map/atcommand.c
  src/map/battle.c
  src/map/battle.h
  src/map/clif.c
  src/map/map.c
  src/map/map.h
  src/map/npc.c
  src/map/script.c
  src/map/script.h
Labels: component:core:scriptengine, component:scripts, type:enhancement

#2798 Refactor scripts that use OnTouch Logic to use areawarp instead
  npc/jobs/2-1/wizard.txt
  npc/quests/quests_juperos.txt
  npc/quests/quests_lighthalzen.txt
  npc/quests/seals/god_weapon_creation.txt
  npc/quests/the_sign_quest.txt
Labels: complexity: 2-moderate, component:scripts, severity:3-medium, type:bug, type:enhancement

#2795 Enable item atcommand to have optional parameters
  src/map/atcommand.c
Labels: type:enhancement

#2647 Fixed Experience Gain message
  conf/messages.conf
  src/map/pc.c
Labels: component:other, severity:2-fair, type:bug

#2790 Add bonuses to reduce received damage based on attacker's defense element
  db/constants.conf
  db/re/item_combo_db.conf
  db/re/item_db.conf
  doc/item_bonus.md
  src/map/battle.c
  src/map/map.h
  src/map/pc.c
  src/map/pc.h
Labels: component:databases, component:documentation, component:mechanics, mode:renewal, status:code-review, status:needs-squashing, type:enhancement
