Repository HerculesWS/Hercules, pull requests merged in 2020-12, with the labels that each got.

#2783 Refactor unit.c - Part II
  src/map/battle.c
  src/map/battle.h
  src/map/elemental.c
  src/map/mob.c
  src/map/npc.c
  src/map/npc.h
  src/map/path.c
  src/map/path.h
  src/map/pc.c
  src/map/pet.c
  src/map/script.c
  src/map/skill.c
  src/map/status.c
  src/map/unit.c
  src/map/unit.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: complexity: 2-moderate, component:core, component:documentation, hacktoberfest-accepted, status:code-review, type:enhancement

#2904 Add static assertion checks to prevent MAX_STORAGE and MAX_GUILD_STORAGE from causing oversized inter-server packets
  src/char/mapif.c
  src/common/mmo.h
  src/map/intif.c
Labels: component:core, status:code-review, type:enhancement

#2903 Fix import schema warning
  sql-files/item_db.sql
  sql-files/item_db2.sql
  sql-files/item_db_re.sql
  sql-files/main.sql
  sql-files/mob_db.sql
  sql-files/mob_db2.sql
  sql-files/mob_db_re.sql
  sql-files/mob_skill_db.sql
  sql-files/mob_skill_db2.sql
  sql-files/mob_skill_db_re.sql
  sql-files/upgrades/2013-02-14--16-15.sql
  sql-files/upgrades/2013-03-05--01-05.sql
  sql-files/upgrades/2013-03-09--01-56.sql
  sql-files/upgrades/2013-03-27--18-35.sql
  sql-files/upgrades/2013-04-16--02-15.sql
  sql-files/upgrades/2013-10-10--16-36.sql
  sql-files/upgrades/2013-10-27--16-47.sql
  sql-files/upgrades/2013-10-30--19-53.sql
  sql-files/upgrades/2013-10-30--21-12.sql
  sql-files/upgrades/2013-10-31--07-49.sql
  sql-files/upgrades/2013-11-09--00-03.sql
  sql-files/upgrades/2013-11-15--00-06.sql
  sql-files/upgrades/2013-11-16--07-49.sql
  sql-files/upgrades/2013-11-18--08-23.sql
  sql-files/upgrades/2013-12-24--00-15.sql
  sql-files/upgrades/2014-01-04--16-47.sql
  sql-files/upgrades/2014-01-06--17-22.sql
  sql-files/upgrades/2014-03-25--23-57.sql
  sql-files/upgrades/2014-04-07--22-04.sql
  sql-files/upgrades/2014-04-26--10-00.sql
  sql-files/upgrades/2014-05-17--00-06.sql
  sql-files/upgrades/2014-09-01--16-53.sql
  sql-files/upgrades/2015-07-02--18-14.sql
  sql-files/upgrades/2015-08-27--20-42.sql
  sql-files/upgrades/2015-12-16--12-57.sql
  sql-files/upgrades/2015-12-17--15-58.sql
  sql-files/upgrades/2016-10-03--20-27.sql
  sql-files/upgrades/2017-03-02--11-40.sql
  sql-files/upgrades/2017-03-05--08-09.sql
  sql-files/upgrades/2017-03-15--14-29.sql
  sql-files/upgrades/2017-06-04--15-04.sql
  sql-files/upgrades/2017-11-04--10-39.sql
  sql-files/upgrades/2018-02-26--15-57.sql
  sql-files/upgrades/2018-03-10--04-06.sql
  sql-files/upgrades/2018-06-03--00-10.sql
  sql-files/upgrades/2018-06-03--17-16.sql
  sql-files/upgrades/2018-06-05--12-02.sql
  sql-files/upgrades/2018-09-01--05-22.sql
  sql-files/upgrades/2018-12-14--01-02.sql
  sql-files/upgrades/2018-12-29--07-51.sql
  sql-files/upgrades/2019-04-25--02-12.sql
  sql-files/upgrades/2019-05-09--18-07.sql
  sql-files/upgrades/2019-10-05--19-01.sql
  sql-files/upgrades/2020-01-24--01-09.sql
  sql-files/upgrades/2020-08-15--13-00.sql
  sql-files/upgrades/eAthena-logs-upgrade.sql
  sql-files/upgrades/eAthena-main-upgrade.sql
  sql-files/upgrades/rAthena-logs-upgrade.sql
  sql-files/upgrades/rAthena-main-upgrade.sql
Labels: component:SQL, status:code-review, type:enhancement

#2883 Prevent farming exploits at Cursed Spirit NPC
  npc/cities/niflheim.txt
Labels: complexity: 0-trivial, component:scripts, hacktoberfest-accepted, severity:2-fair

#2855 Fix incorrect looting behavior with monster_loot_type battle config
  src/map/mob.c
Labels: complexity: 1-straightforward, component:mechanics, hacktoberfest-accepted, severity:2-fair, type:enhancement
