Repository HerculesWS/Hercules, pull requests merged in 2020-10, with the labels that each got.

#2863 Adjusted KO_ZENKAI AoE Effect
  src/map/skill.c
Labels: component:mechanics:skills, status:code-review

#2857 Refactor NPC parse mapflag codes
  src/map/npc.c
Labels: component:core

#2856 Fix BaseClass misuse
  npc/quests/bard_quest.txt
  npc/quests/quests_13_1.txt
  npc/quests/quests_ein.txt
  npc/quests/quests_morocc.txt
  npc/quests/quests_nameless.txt
Labels: complexity: 2-moderate, component:scripts

#2850 Update *getcartinventorylist documentation
  doc/script_commands.txt
Labels: codereview:needsedits, component:documentation

#2876 Allow to pass an account id to getcharid
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement
