Repository HerculesWS/Hercules, pull requests merged in 2020-11, with the labels that each got.

#2878 Update hat effect constant list.
  db/constants.conf
Labels: hacktoberfest-accepted

#2879 Update NPC ID constant.
  db/constants.conf
  src/map/npc.h
Labels: hacktoberfest-accepted

#2231 Refactored Party Booking defines.
  src/map/clif.c
  src/map/party.c
  src/map/party.h
Labels: component:core

#2048 Update waitingroom script commands.
  doc/script_commands.txt
  src/map/script.c
Labels: component:core:scriptengine, component:documentation, type:enhancement

#2882 Refactor map->random_dir and implement aegis behavior of some skills which used it
  db/pre-re/skill_db.conf
  db/re/skill_db.conf
  src/map/map.c
  src/map/map.h
  src/map/skill.c
  src/map/unit.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: complexity: 1-straightforward, component:mechanics, hacktoberfest-accepted, severity:1-trivial

#2881 Allow override libconfig command @include
  3rdparty/libconfig/scanctx.c
  src/common/conf.c
Labels: hacktoberfest-accepted

#2873 Fix Freezing Spear on Watery Evasion
  src/map/battle.c
Labels: hacktoberfest-accepted

#2884 improve error messages in mob skill db to show monster constants
  src/map/mob.c
Labels: component:core, hacktoberfest-accepted, status:code-review, type:enhancement

#2885 Fix nullpo error in searchstore
  src/map/clif.c
  src/map/searchstore.c
Labels: component:core, hacktoberfest-accepted, status:code-review, type:enhancement

#2887 Fix some wrong return values in mob skill code
  src/map/battle.c
  src/map/mob.c
  src/map/mob.h
  src/map/skill.c
  src/map/unit.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core, hacktoberfest-accepted, status:code-review, type:bug

#2888 Fix summoned monsters wont follow masters of type BL_PC
  src/map/mob.c
Labels: component:core, hacktoberfest-accepted, status:code-review, type:bug

#2890 Make Impositio Manus always overwrites itself
  src/map/status.c
Labels: component:mechanics:skills, status:code-review, type:bug

#2891 Prevent using unit->set_dir needlessly in unit_attack_timer_sub
  src/map/unit.c
Labels: complexity: 0-trivial

#2894 fix pc_calc_pvprank_sub cannot hook by plugin
  src/map/pc.c
  src/map/pc.h
Labels: component:core, status:code-review, type:enhancement

#2900 Fix map server crash when changing display class of floating NPC
  src/map/npc.c
Labels: component:core:scriptengine, status:code-review, type:bug

#2901 Add some data evaluation to the RODEX send mail script commands
  src/map/script.c
Labels: component:core:scriptengine, status:code-review, type:bug

#2902 Add missing "Card" suffix to Fruit Pom Spider Card
  db/re/item_db.conf
Labels: component:databases, mode:renewal, status:code-review, type:bug

#2831 Fixed KO_GENWAKU Swap Effect
  src/map/skill.c
Labels: component:mechanics:skills, mode:renewal, status:code-review, type:bug
