Repository HerculesWS/Hercules, pull requests merged in 2021-12, with the labels that each got.

#3088 Fix countnameditem() always returning 0
  src/map/script.c
Labels: type:bug

#3065 Enable *makeitem to display DropEffect
  doc/script_commands.txt
  src/map/script.c
Labels: type:enhancement, component:core:scriptengine, hacktoberfest-accepted

#3067 Fixes #3027 - Allows variable to be passed in rodex_sendmail
  src/map/script.c
Labels: hacktoberfest-accepted

#3073 Adds active_transform script command
  db/constants.conf
  db/pre-re/sc_config.conf
  db/re/sc_config.conf
  doc/script_commands.txt
  src/map/atcommand.c
  src/map/clif.c
  src/map/script.c
  src/map/status.c
  src/map/status.h
Labels: status:needs-rebase, hacktoberfest-accepted

#3096 Fix an error causing conditional feature checks to always be true
  src/map/script.c
Labels: type:bug, component:core:scriptengine
