Repository HerculesWS/Hercules, pull requests merged in 2021-02, with the labels that each got.

#2911 Introduce map border for map->search_freecell, fixing dead cell bugs.
  conf/map/battle/misc.conf
  src/map/atcommand.c
  src/map/battle.c
  src/map/battle.h
  src/map/elemental.c
  src/map/map.c
  src/map/map.h
  src/map/mob.c
  src/map/script.c
  src/map/skill.c
  src/map/unit.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: complexity: 2-moderate, component:configuration, component:mechanics

#2874 Add more options to the quest database
  db/quest_db.conf
  src/map/clif.c
  src/map/mob.c
  src/map/quest.c
  src/map/quest.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
  tools/HPMHookGen/HPMHookGen.pl
Labels: status:code-review

#2886 Allow constants on QuestDB
  db/pre-re/item_db.conf
  db/quest_db.conf
  src/map/quest.c
  src/map/quest.h
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc
  src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: hacktoberfest-accepted
