Repository HerculesWS/Hercules, pull requests merged in 2021-01, with the labels that each got.

#2921 Fix a part of sign quest becoming unfinishable for everyone
  npc/quests/the_sign_quest.txt
Labels: complexity: 2-moderate, component:scripts, severity:3-medium, type:bug

#2875 Update MVP DamageTakenRate
  db/pre-re/mob_db.conf
  db/re/mob_db.conf
Labels: component:databases, hacktoberfest-accepted

#2807 Check for homunculus skills requisites before leveling it up.
  src/map/homunculus.c
Labels: component:mechanics, status:code-review, type:enhancement

#2858 Update *mercenary_delete
  doc/script_commands.txt
  src/map/clif.c
  src/map/mercenary.c
  src/map/mercenary.h
  src/map/pc.c
  src/map/script.c
  src/map/status.c
  src/plugins/HPMHooking/HPMHooking.Defs.inc
  src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Labels: component:core:scriptengine, component:documentation, hacktoberfest-accepted
